name: "Lean On Me"
description: "Lean On Me Blog"

url: "http://lean0n.me"

baseurl: /blog

paginate: 5
paginate_path: "blog/page:num/"
markdown: rdiscount
permalink: pretty
highlighter: pygments
gems:
    - jekyll-redirect-from
